name = "f4club"
main = "dist/_worker.js/index.js"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "f4club-db"
database_id = "ee96b330-fb2b-4746-a26d-ba5cb3f70ab9"

[[kv_namespaces]]
binding = "SESSIONS"
id = "8ffdbbeac95247b18cd774886e05e2bf"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "f4club-default"
